export const ALL_CONTACT_U_REQUEST = "ALL_CONTACT_U_REQUEST";
export const ALL_CONTACT_U_SUCCESS = "ALL_CONTACT_U_SUCCESS";
export const ALL_CONTACT_U_FAIL = "ALL_CONTACT_U_FAIL";

export const CLEAR_ERRORS = "CLEARE_ERRORS";
