export const SAVE_P_INFO_U_REQUEST = "SAVE_P_INFO_U_REQUEST";
export const SAVE_P_INFO_U_SUCCESS = "SAVE_P_INFO_U_SUCCESS";
export const SAVE_P_INFO_U_FAIL = "SAVE_P_INFO_U_FAIL";
export const SAVE_P_INFO_U_RESET = "SAVE_P_INFO_U_RESET";

export const SAVE_SKILLS_U_REQUEST = "SAVE_SKILLS_U_REQUEST";
export const SAVE_SKILLS_U_SUCCESS = "SAVE_SKILLS_U_SUCCESS";
export const SAVE_SKILLS_U_FAIL = "SAVE_SKILLS_U_FAIL";
export const SAVE_SKILLS_U_RESET = "SAVE_SKILLS_U_RESET";

export const SAVE_PROFILE_PIC_U_REQUEST = "SAVE_PROFILE_PIC_REQUEST";
export const SAVE_PROFILE_PIC_SUCCESS = "SAVE_PROFILE_PIC_SUCCESS";
export const SAVE_PROFILE_PIC_FAIL = "SAVE_PROFILE_PIC_FAIL";
export const SAVE_PROFILE_PIC_RESET = "SAVE_PROFILE_PIC_RESET";

export const SAVE_CONTACT_URL_U_REQUEST = "SAVE_CONTACT_URL_U_REQUEST";
export const SAVE_CONTACT_URL_U_SUCCESS = "SAVE_CONTACT_URL_U_SUCCESS";
export const SAVE_CONTACT_URL_U_FAIL = "SAVE_CONTACT_URL_U_FAIL";
export const SAVE_CONTACT_URL_U_RESET = "SAVE_CONTACT_URL_U_RESET";

export const MY_PORTFOLIO_U_REQUEST = "MY_PORTFOLIO_U_REQUEST";
export const MY_PORTFOLIO_U_SUCCESS = "MY_PORTFOLIO_U_SUCCESS";
export const MY_PORTFOLIO_U_FAIL = "MY_PORTFOLIO_U_FAIL";

export const CLEAR_ERRORS = "CLEARE_ERRORS";
