export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const LOGGED_IN_USER_REQUEST = "LOGGED_IN_USER_REQUEST";
export const LOGGED_IN_USER_SUCCESS = "LOGGED_IN_USER_SUCCESS";
export const LOGGED_IN_USER_FAIL = "LOGGED_IN_USER_FAIL";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";

export const CLEAR_ERRORS = "CLEARE_ERRORS";
