export const ALL_PROJECT_U_REQUEST = "ALL_PROJECT_U_REQUEST";
export const ALL_PROJECT_U_SUCCESS = "ALL_PROJECT_U_SUCCESS";
export const ALL_PROJECT_U_FAIL = "ALL_PROJECT_U_FAIL";

export const ADD_PROJECT_U_REQUEST = "ADD_PROJECT_U_REQUEST";
export const ADD_PROJECT_U_SUCCESS = "ADD_PROJECT_U_SUCCESS";
export const ADD_PROJECT_U_FAIL = "ADD_PROJECT_U_FAIL";
export const ADD_PROJECT_U_RESET = "ADD_PROJECT_U_RESET";

export const PROJECT_DETAIL_U_REQUEST = "PROJECT_DETAIL_U_REQUEST";
export const PROJECT_DETAIL_U_SUCCESS = "PROJECT_DETAIL_U_SUCCESS";
export const PROJECT_DETAIL_U_FAIL = "PROJECT_DETAIL_U_FAIL";

export const PROJECT_UPDATE_U_REQUEST = "PROJECT_UPDATE_U_REQUEST";
export const PROJECT_UPDATE_U_SUCCESS = "PROJECT_UPDATE_U_SUCCESS";
export const PROJECT_UPDATE_U_FAIL = "PROJECT_UPDATE_U_FAIL";
export const PROJECT_UPDATE_U_RESET = "PROJECT_UPDATE_U_RESET";

export const DELETE_PROJECT_U_REQUEST = "DELETE_PROJECT_U_REQUEST";
export const DELETE_PROJECT_U_SUCCESS = "DELETE_PROJECT_U_SUCCESS";
export const DELETE_PROJECT_U_FAIL = "DELETE_PROJECT_U_FAIL";
export const DELETE_PROJECT_U_RESET = "DELETE_PROJECT_U_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
