export const ALL_CONTACT_A_REQUEST = "ALL_CONTACT_A_REQUEST";
export const ALL_CONTACT_A_SUCCESS = "ALL_CONTACT_A_SUCCESS";
export const ALL_CONTACT_A_FAIL = "ALL_CONTACT_A_FAIL";

export const CLEAR_ERRORS = "CLEARE_ERRORS";
