export const DELETE_PROJECT_A_REQUEST = "DELETE_PROJECT_A_REQUEST";
export const DELETE_PROJECT_A_SUCCESS = "DELETE_PROJECT_A_SUCCESS";
export const DELETE_PROJECT_A_FAIL = "DELETE_PROJECT_A_FAIL";
export const DELETE_PROJECT_A_RESET = "DELETE_PROJECT_A_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";