export const SAVE_PORTFOLIO_A_REQUEST = "SAVE_PORTFOLIO_A_REQUEST";
export const SAVE_PORTFOLIO_A_SUCCESS = "SAVE_PORTFOLIO_A_SUCCESS";
export const SAVE_PORTFOLIO_A_FAIL = "SAVE_PORTFOLIO_A_FAIL";

export const MY_PORTFOLIO_A_REQUEST = "MY_PORTFOLIO_A_REQUEST";
export const MY_PORTFOLIO_A_SUCCESS = "MY_PORTFOLIO_A_SUCCESS";
export const MY_PORTFOLIO_A_FAIL = "MY_PORTFOLIO_A_FAIL";

export const UPDATE_PORTFOLIO_A_REQUEST = "UPDATE_PORTFOLIO_A_REQUEST";
export const UPDATE_PORTFOLIO_A_SUCCESS = "UPDATE_PORTFOLIO_A_SUCCESS";
export const UPDATE_PORTFOLIO_A_FAIL = "UPDATE_PORTFOLIO_A_FAIL";

export const CLEAR_ERRORS = "CLEARE_ERRORS";
